#ifndef BME280MGR_H
#define BME280MGR_H

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "string.h"

#include "sdkconfig.h" // Generated by "idf.py menuconfig"

#include "bme280.h" // From the Bosch BME280 component

#define SDA_PIN GPIO_NUM_8
#define SCL_PIN GPIO_NUM_9

#define TAG_BME280 "BME280"

#define I2C_MASTER_ACK 0
#define I2C_MASTER_NACK 1

// I2C master initialization
void i2c_master_init();
s8 BME280_I2C_bus_write(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt);
s8 BME280_I2C_bus_read(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt);
void BME280_delay_msek(u32 msek);
void bme280_reader_task(void *ignore);
void bme280start(void);

#endif